// File generated by FlutterFire CLI.
// Run `flutterfire configure` to replace these placeholders with your Firebase project config.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

//I'm editting the file
import 'dart:io' show Platform;

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isMacOS) return macos;
    if (Platform.isIOS) return ios;
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PLACEHOLDER_RUN_FLUTTERFIRE_CONFIGURE',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'rizzrank-placeholder',
    storageBucket: 'rizzrank-placeholder.appspot.com',
    databaseURL: 'https://rizzrank-placeholder-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'PLACEHOLDER_RUN_FLUTTERFIRE_CONFIGURE',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'rizzrank-placeholder',
    storageBucket: 'rizzrank-placeholder.appspot.com',
    iosBundleId: 'com.example.rizzrank',
    databaseURL: 'https://rizzrank-placeholder-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'PLACEHOLDER_RUN_FLUTTERFIRE_CONFIGURE',
    appId: '1:000000000000:macos:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'rizzrank-placeholder',
    storageBucket: 'rizzrank-placeholder.appspot.com',
    iosBundleId: 'com.example.rizzrank',
    databaseURL: 'https://rizzrank-placeholder-default-rtdb.firebaseio.com',
  );
}
