// File generated by FlutterFire CLI.
// Run `flutterfire configure` to replace these placeholders with your Firebase project config.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:371372966416:web:2ebab7e19fa0418e6f4095',
    messagingSenderId: '371372966416',
    projectId: 'rizzrank-f52cd',
    authDomain: 'rizzrank-f52cd.firebaseapp.com',
    databaseURL: 'https://rizzrank-f52cd-default-rtdb.firebaseio.com',
    storageBucket: 'rizzrank-f52cd.firebasestorage.app',
    measurementId: 'G-KM1LZS16GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:371372966416:android:8adc920b56317d7e6f4095',
    messagingSenderId: '371372966416',
    projectId: 'rizzrank-f52cd',
    databaseURL: 'https://rizzrank-f52cd-default-rtdb.firebaseio.com',
    storageBucket: 'rizzrank-f52cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:371372966416:ios:be2c393dc9e3e2e26f4095',
    messagingSenderId: '371372966416',
    projectId: 'rizzrank-f52cd',
    databaseURL: 'https://rizzrank-f52cd-default-rtdb.firebaseio.com',
    storageBucket: 'rizzrank-f52cd.firebasestorage.app',
    iosClientId: '371372966416-nt8jo8om1g15i4kkmmsi10vi0g0c07j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.rizzrank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:371372966416:ios:be2c393dc9e3e2e26f4095',
    messagingSenderId: '371372966416',
    projectId: 'rizzrank-f52cd',
    databaseURL: 'https://rizzrank-f52cd-default-rtdb.firebaseio.com',
    storageBucket: 'rizzrank-f52cd.firebasestorage.app',
    iosClientId: '371372966416-nt8jo8om1g15i4kkmmsi10vi0g0c07j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.rizzrank',
  );

}