// File generated by FlutterFire CLI.
// Run `flutterfire configure` to replace these placeholders with your Firebase project config.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'dart:io' show Platform;

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isMacOS) return macos;
    if (Platform.isIOS) return ios;
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD22vLRdxm78bR91QRAHYyRdZLDXSPZ0Tg',
    appId: '1:371372966416:android:8adc920b56317d7e6f4095',
    messagingSenderId: '371372966416',
    projectId: 'rizzrank-f52cd',
    databaseURL: 'https://rizzrank-f52cd-default-rtdb.firebaseio.com',
    storageBucket: 'rizzrank-f52cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWkA5bVVI5CUoDKYbpVennn3taoAkKRnA',
    appId: '1:371372966416:ios:be2c393dc9e3e2e26f4095',
    messagingSenderId: '371372966416',
    projectId: 'rizzrank-f52cd',
    databaseURL: 'https://rizzrank-f52cd-default-rtdb.firebaseio.com',
    storageBucket: 'rizzrank-f52cd.firebasestorage.app',
    iosClientId: '371372966416-nt8jo8om1g15i4kkmmsi10vi0g0c07j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.rizzrank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWkA5bVVI5CUoDKYbpVennn3taoAkKRnA',
    appId: '1:371372966416:ios:be2c393dc9e3e2e26f4095',
    messagingSenderId: '371372966416',
    projectId: 'rizzrank-f52cd',
    databaseURL: 'https://rizzrank-f52cd-default-rtdb.firebaseio.com',
    storageBucket: 'rizzrank-f52cd.firebasestorage.app',
    iosClientId: '371372966416-nt8jo8om1g15i4kkmmsi10vi0g0c07j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.rizzrank',
  );

}