/**
 * All trait category data for AI model personas.
 * Each category maps to an array of possible values.
 * During matchmaking, one value is randomly selected per category
 * to compose a unique AI persona for each match.
 */

export interface TraitData {
  [category: string]: string[];
}

export const TRAIT_DATA: TraitData = {
  heights: [
    "<4'0",
    "4'1 - 4'6",
    "4'7 - 4'11",
    "5'0 - 5'5",
    "5'6 - 5'10",
    "5'11 - 6'3",
    "6'4 - 6'8",
    "6'9 - 7'0",
    "7'1+",
  ],

  ages: [
    "18 - 23",
    "24-29",
    "30-35",
    "36-41",
    "42-47",
    "48-53",
  ],

  hobbies: [
    "Acting",
    "Aeromodeling",
    "Air sports",
    "Airbrushing",
    "Aircraft Spotting",
    "Airsoft",
    "Airsofting",
    "Amateur astronomy",
    "Amateur geology",
    "Amateur Radio",
    "American football",
    "Animal fancy",
    "Dogs",
    "Pets",
    "Animals",
    "Antiquing",
    "Antiquities",
    "Aqua-lung",
    "Aquarium",
    "Archery",
    "Art collecting",
    "Arts",
    "Association football",
    "Astrology",
    "Astronomy",
    "Audiophilia",
    "Auto audiophilia",
    "Auto racing",
    "Backgammon",
    "Backpacking",
    "Badminton",
    "Base Jumping",
    "Baseball",
    "Basketball",
    "Baton Twirling",
    "Beach Volleyball",
    "Sun tanning",
    "Beach",
    "Beachcombing",
    "Beadwork",
    "Beatboxing",
    "Beekeeping",
    "Bell Ringing",
    "Belly Dancing",
    "Bicycle Polo",
    "Bicycling",
    "Billiards",
    "Bird watching",
    "Birding",
    "Birdwatching",
    "Blacksmithing",
    "Blogging",
    "BMX",
    "Board games",
    "Board sports",
    "BoardGames",
    "Boating",
    "Body Building",
    "Bodybuilding",
    "Bonsai Tree",
    "Book collecting",
    "Bookbinding",
    "Boomerangs",
    "Bowling",
    "Boxing",
    "Brazilian jiu-jitsu",
    "Breakdancing",
    "Brewing Beer",
    "Bridge",
    "Bridge Building",
    "Bringing Food To The Disabled",
    "Building Dollhouses",
    "Bus spotting",
    "Butterfly Watching",
    "Button Collecting",
    "Cake Decorating",
    "Calligraphy",
    "Camping",
    "Candle making",
    "Canoeing",
    "Car Racing",
    "Card collecting",
    "Cartooning",
    "Casino Gambling",
    "Cave Diving",
    "Ceramics",
    "Cheerleading",
    "Chess",
    "Church/church activities",
    "Cigar Smoking",
    "Climbing",
    "Cloud Watching",
    "Coin Collecting",
    "Collecting",
    "Collecting Antiques",
    "Collecting Artwork",
    "Collecting Hats",
    "Collecting Music Albums",
    "Collecting RPM Records",
    "Collecting Sports Cards",
    "Collecting Swords",
    "Color guard",
    "Coloring",
    "Comic book collecting",
    "Compose Music",
    "Computer activities",
    "Computer programming",
    "Conworlding",
    "Cooking",
    "Cosplay",
    "Cosplaying",
    "Couponing",
    "Crafts",
    "Creative writing",
    "Cricket",
    "Crochet",
    "Crocheting",
    "Cross-Stitch",
    "Crossword Puzzles",
    "Cryptography",
    "Curling",
    "Cycling",
    "Dance",
    "Dancing",
    "Darts",
    "Debate",
    "Deltiology",
    "Diecast Collectibles",
    "Digital arts",
    "Digital Photography",
    "Disc golf",
    "Do it yourself",
    "Dodgeball",
    "Dog sport",
    "Dolls",
    "Dominoes",
    "Dowsing",
    "Drama",
    "Drawing",
    "Driving",
    "Dumpster Diving",
    "Eating out",
    "Educational Courses",
    "Electronics",
    "Element collecting",
    "Embroidery",
    "Entertaining",
    "Equestrianism",
    "Aerobics",
    "Exercise",
    "Exhibition drill",
    "Falconry",
    "Fast cars",
    "Felting",
    "Fencing",
    "Field hockey",
    "Figure skating",
    "Fire Poi",
    "Fishing",
    "Fishkeeping",
    "Flag Football",
    "Floorball",
    "Floral Arrangements",
    "Flower arranging",
    "Flower collecting and pressing",
    "Fly Tying",
    "Flying",
    "Footbag",
    "Football",
    "Foraging",
    "Foreign language learning",
    "Fossil hunting",
    "Four Wheeling",
    "Freshwater Aquariums",
    "Frisbee Golf",
    "Gambling",
    "Games",
    "Gaming",
    "Garage Saleing",
    "Gardening",
    "Genealogy",
    "Geocaching",
    "Ghost hunting",
    "Glassblowing",
    "Glowsticking",
    "Gnoming",
    "Going to movies",
    "Golf",
    "Golfing",
    "Gongoozling",
    "Graffiti",
    "Grip Strength",
    "Guitar",
    "Gun Collecting",
    "Gunsmithing",
    "Gymnastics",
    "Gyotaku",
    "Handball",
    "Handwriting Analysis",
    "Hang gliding",
    "Herping",
    "Hiking",
    "Home Brewing",
    "Home Repair",
    "Home Theater",
    "Homebrewing",
    "Hooping",
    "Horse riding",
    "Hot air ballooning",
    "Hula Hooping",
    "Hunting",
    "Ice hockey",
    "Ice skating",
    "Iceskating",
    "Illusion",
    "Impersonations",
    "Inline skating",
    "Insect collecting",
    "Internet",
    "Inventing",
    "Jet Engines",
    "Jewelry Making",
    "Jigsaw Puzzles",
    "Jogging",
    "Judo",
    "Juggling",
    "Jukskei",
    "Jump Roping",
    "Kabaddi",
    "Kart racing",
    "Kayaking",
    "Keep A Journal",
    "Kitchen Chemistry",
    "Kite Boarding",
    "Kite flying",
    "Kites",
    "Kitesurfing",
    "Knapping",
    "Knife making",
    "Knife throwing",
    "Knitting",
    "Knotting",
    "Lacemaking",
    "Lacrosse",
    "Lapidary",
    "LARPing",
    "Laser tag",
    "Lasers",
    "Lawn Darts",
    "Learn to Play Poker",
    "Learning A Foreign Language",
    "Learning An Instrument",
    "Learning To Pilot A Plane",
    "Leather crafting",
    "Leathercrafting",
    "Lego building",
    "Legos",
    "Letterboxing",
    "Listening to music",
    "Locksport",
    "Machining",
    "Macramé",
    "Macrame",
    "Magic",
    "Mahjong",
    "Making Model Cars",
    "Marbles",
    "Marksmanship",
    "Martial arts",
    "Matchstick Modeling",
    "Meditation",
    "Metal detecting",
    "Meteorology",
    "Microscopy",
    "Mineral collecting",
    "Model aircraft",
    "Model building",
    "Model Railroading",
    "Model Rockets",
    "Modeling Ships",
    "Models",
    "Motor sports",
    "Motorcycles",
    "Mountain Biking",
    "Mountain Climbing",
    "Mountaineering",
    "Movie and movie memorabilia collecting",
    "Mushroom hunting/Mycology",
    "Musical Instruments",
    "Nail Art",
    "Needlepoint",
    "Netball",
    "Nordic skating",
    "Orienteering",
    "Origami",
    "Owning An Antique Car",
    "Paintball",
    "Painting",
    "Papermache",
    "Papermaking",
    "Parachuting",
    "Paragliding or Power Paragliding",
    "Parkour",
    "People Watching",
    "Photography",
    "Piano",
    "Pigeon racing",
    "Pinochle",
    "Pipe Smoking",
    "Planking",
    "Playing music",
    "Playing musical instruments",
    "Playing team sports",
    "Poker",
    "Pole Dancing",
    "Polo",
    "Pottery",
    "Powerboking",
    "Protesting",
    "Puppetry",
    "Puzzles",
    "Pyrotechnics",
    "Quilting",
    "R/C Boats",
    "R/C Cars",
    "R/C Helicopters",
    "R/C Planes",
    "Racing Pigeons",
    "Racquetball",
    "Radio-controlled car racing",
    "Rafting",
    "Railfans",
    "Rappelling",
    "Rapping",
    "Reading",
    "Reading To The Elderly",
    "Record collecting",
    "Relaxing",
    "Renaissance Faire",
    "Renting movies",
    "Rescuing Abused/Abandoned Animals",
    "Robotics",
    "Rock balancing",
    "Rock climbing",
    "Rock Collecting",
    "Rockets",
    "Rocking AIDS Babies",
    "Roleplaying",
    "Roller derby",
    "Roller skating",
    "Rugby",
    "Rugby league football",
    "Running",
    "Sailing",
    "Saltwater Aquariums",
    "Sand art",
    "Sand Castles",
    "Scrapbooking",
    "Scuba diving",
    "Sculling or Rowing",
    "Sculpting",
    "Sea glass collecting",
    "Seashell collecting",
    "Self Defense",
    "Sewing",
    "Shark Fishing",
    "Shooting",
    "Shooting sport",
    "Shopping",
    "Shortwave listening",
    "Singing",
    "Singing In Choir",
    "Skateboarding",
    "Skeet Shooting",
    "Sketching",
    "Skiing",
    "Skimboarding",
    "Sky Diving",
    "Skydiving",
    "Slack Lining",
    "Slacklining",
    "Sleeping",
    "Slingshots",
    "Slot car racing",
    "Snorkeling",
    "Snowboarding",
    "Soap Making",
    "Soapmaking",
    "Socializing with friends/neighbors",
    "Speed Cubing",
    "Speed skating",
    "Spelunkering",
    "Spending time with family/kids",
    "Sports",
    "Squash",
    "Stamp Collecting",
    "Stand-up comedy",
    "Stone collecting",
    "Stone skipping",
    "Storm Chasing",
    "Storytelling",
    "String Figures",
    "Sudoku",
    "Surf Fishing",
    "Surfing",
    "Survival",
    "Swimming",
    "Table football",
    "Table tennis",
    "Taekwondo",
    "Tai chi",
    "Tatting",
    "Taxidermy",
    "Tea Tasting",
    "Tennis",
    "Tesla Coils",
    "Tetris",
    "Textiles",
    "Texting",
    "Tombstone Rubbing",
    "Tool Collecting",
    "Tour skating",
    "Toy Collecting",
    "Train Collecting",
    "Train Spotting",
    "Trainspotting",
    "Traveling",
    "Treasure Hunting",
    "Trekkie",
    "Triathlon",
    "Tutoring Children",
    "TV watching",
    "Ultimate Frisbee",
    "Urban exploration",
    "Vehicle restoration",
    "Video game collecting",
    "Video Games",
    "Video gaming",
    "Videophilia",
    "Vintage cars",
    "Violin",
    "Volleyball",
    "Volunteer",
    "Walking",
    "Warhammer",
    "Watching movies",
    "Watching sporting events",
    "Water sports",
    "Weather Watcher",
    "Web surfing",
    "Weightlifting",
    "Windsurfing",
    "Wine Making",
    "Wood carving",
    "Woodworking",
    "Working In A Food Pantry",
    "Working on cars",
    "World Record Breaking",
    "Worldbuilding",
    "Wrestling",
    "Writing",
    "Writing Music",
    "Writing Songs",
    "Yo-yoing",
    "Yoga",
    "YoYo",
    "Ziplining",
    "Zumba",
  ],

  personality_traits: [
    "Shy",
    "Extroverted",
    "Introverted",
    "Charismatic",
    "Blunt",
    "Diplomatic",
    "Witty",
    "Reserved",
    "Gregarious",
    "Aloof",
    "Stoic",
    "Cynical",
    "Resilient",
    "Ambitious",
    "Meticulous",
    "Analytical",
    "Procrastinator",
    "Decisive",
    "Creative",
    "Pragmatic",
    "Diligent",
    "Absent-minded",
    "Inquisitive",
    "Altruistic",
    "Honest",
    "Loyal",
    "Manipulative",
    "Empathetic",
    "Arrogant",
    "Humble",
    "Principled",
    "Sincere",
    "Callous",
    "Spontaneous",
    "Easygoing",
    "Assertive",
    "Methodical",
    "Whimsical",
    "Compassionate",
  ],

  moods: [
    "Happy",
    "Melancholic",
    "Volatile",
    "Serene",
    "Anxious",
    "Optimistic",
    "Pessimistic",
    "Vibrant",
    "Mellow",
    "Exuberant",
    "Grumpy",
  ],

  ethnicities: [
    "African",
    "African American",
    "Arab",
    "Asian",
    "Asian American",
    "Bengali",
    "Black",
    "Caribbean",
    "Chinese",
    "Dutch",
    "English",
    "Filipino",
    "French",
    "German",
    "Greek",
    "Hispanic/Latino",
    "Indian",
    "Indigenous/Native American",
    "Irish",
    "Italian",
    "Japanese",
    "Jewish",
    "Korean",
    "Malay",
    "Mexican",
    "Middle Eastern",
    "Native Hawaiian/Pacific Islander",
    "Pakistani",
    "Polish",
    "Russian",
    "Scottish",
    "Spanish",
    "Thai",
    "Vietnamese",
    "White",
  ],

  genders: [
    "Man",
    "Woman",
    "Other",
  ],

  communication_styles: [
    "Impatient, quick",
    "Verbose, slow",
    "Casual",
    "Formal",
  ],

  careers: [
    "Accountant",
    "Architect",
    "Aerospace Engineer",
    "Art Director",
    "Attorney",
    "Biologist",
    "Biomedical Engineer",
    "Carpenter",
    "Chef",
    "Civil Engineer",
    "Computer Systems Analyst",
    "Content Writer",
    "Customer Service Representative",
    "Data Scientist",
    "Dental Hygienist",
    "Dentist",
    "Electrician",
    "Elementary School Teacher",
    "Environmental Scientist",
    "Fashion Designer",
    "Financial Advisor",
    "Firefighter",
    "Graphic Designer",
    "Human Resources Manager",
    "Interior Designer",
    "Investment Banker",
    "IT Support Specialist",
    "Journalist",
    "Librarian",
    "Logistics Manager",
    "Marketing Manager",
    "Mechanical Engineer",
    "Medical Assistant",
    "Nurse",
    "Occupational Therapist",
    "Paramedic",
    "Pharmacist",
    "Photographer",
    "Physical Therapist",
    "Physician",
    "Pilot",
    "Plumber",
    "Police Officer",
    "Professor",
    "Psychologist",
    "Real Estate Agent",
    "Social Worker",
    "Software Developer",
    "Speech-Language Pathologist",
    "Statistician",
    "Surgeon",
    "UX Designer",
    "Veterinarian",
    "Video Editor",
    "Web Developer",
  ],

  love_languages: [
    "Words of Affirmation",
    "Acts of Service",
    "Receiving Gifts",
    "Quality Time",
    "Physical Touch",
  ],

  intelligence: [
    "145+",
    "130-144",
    "120-129",
    "110-119",
    "90-109",
    "80-89",
    "70-79",
    "55-69",
    "40-54",
    "25-39",
    "<25",
  ],

  social_penetration_theory: [
    "Yapper",
    "Listener",
    "Middle ground listener",
  ],
};

/** All trait category keys. */
export const TRAIT_CATEGORIES = Object.keys(TRAIT_DATA) as (keyof typeof TRAIT_DATA)[];

/** Picks one random value from each trait category. */
export function pickRandomTraits(): Record<string, string> {
  const result: Record<string, string> = {};
  for (const category of TRAIT_CATEGORIES) {
    const values = TRAIT_DATA[category];
    result[category] = values[Math.floor(Math.random() * values.length)];
  }
  return result;
}

function pickRandom<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function pickN<T>(arr: T[], n: number): T[] {
  const shuffled = [...arr].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, n);
}

const FIRST_NAMES = [
  "Alex", "Jordan", "Sam", "Riley", "Morgan", "Casey", "Avery", "Quinn",
  "Skyler", "Reese", "Dakota", "Parker", "Cameron", "Blake", "Drew",
  "Emery", "Finley", "Harper", "Jamie", "Kendall", "Logan", "Marley",
  "Noah", "Oakley", "Peyton", "River", "Sage", "Taylor", "Charlie",
];

/** Picks dynamic traits for a generated AI character. preferredGender: Man | Woman | Other. */
export function pickDynamicTraits(preferredGender: string): Record<string, string> {
  const result: Record<string, string> = {};
  result.ages = pickRandom(TRAIT_DATA.ages);
  result.careers = pickRandom(TRAIT_DATA.careers);
  result.communication_styles = pickRandom(TRAIT_DATA.communication_styles);
  result.ethnicities = pickRandom(TRAIT_DATA.ethnicities);
  result.genders = preferredGender;
  result.heights = pickRandom(TRAIT_DATA.heights);
  const hobbies = pickN(TRAIT_DATA.hobbies, 3);
  result.hobbies = hobbies.join(", ");
  result.intelligence = pickRandom(TRAIT_DATA.intelligence);
  const loveLangs = pickN(TRAIT_DATA.love_languages, 2);
  result.love_languages = loveLangs.join(" and ");
  result.moods = pickRandom(TRAIT_DATA.moods);
  result.personality_traits = pickRandom(TRAIT_DATA.personality_traits);
  result.social_penetration_theory = pickRandom(TRAIT_DATA.social_penetration_theory);
  return result;
}

/** Generates a random character name. */
export function generateCharacterName(): string {
  return pickRandom(FIRST_NAMES);
}

/** Builds the full system prompt for a dynamic AI character. */
export function buildDynamicSystemPrompt(traits: Record<string, string>, name: string): string {
  const parts: string[] = [];
  if (traits.genders) parts.push(`You are a ${traits.genders}.`);
  if (traits.ages) parts.push(`You are ${traits.ages} years old.`);
  if (traits.heights) parts.push(`You are ${traits.heights} tall.`);
  if (traits.ethnicities) parts.push(`Your ethnicity is ${traits.ethnicities}.`);
  if (traits.careers) parts.push(`You work as a ${traits.careers}.`);
  if (traits.hobbies) parts.push(`Your hobbies include: ${traits.hobbies}.`);
  if (traits.personality_traits) parts.push(`Your personality is ${traits.personality_traits}.`);
  if (traits.moods) parts.push(`Your current mood is ${traits.moods}.`);
  if (traits.communication_styles) parts.push(`Your communication style is ${traits.communication_styles}.`);
  if (traits.love_languages) parts.push(`Your love languages are ${traits.love_languages}.`);
  if (traits.intelligence) parts.push(`Your IQ range is ${traits.intelligence}.`);
  if (traits.social_penetration_theory) parts.push(`In conversation you are a ${traits.social_penetration_theory}.`);

  const personaBlock = parts.join(" ");
  return `You are ${name}. ${personaBlock}

You are currently in a 'Rizz' battle with the user. Be challenging but potentially winnable if they show real wit or charm. Keep responses concise and in character.`;
}

const OPENING_LINES = [
  "Hey, so... what brings you here?",
  "Alright, let's see what you've got.",
  "Interesting. I usually don't stick around for small talk.",
  "So you think you can keep up? We'll see.",
  "Honestly, I'm not easily impressed. Change my mind?",
];

/** Returns a random opening line for a dynamic character. */
export function getDynamicOpeningLine(): string {
  return pickRandom(OPENING_LINES);
}
